### ISSUE TITLE
Fail to run tile build in my ubuntu 

### ISSUE THREAD

**Issue by dwu-pivotal** [cf-platform-eng/tile-generator#13]
➜  sample git:(master) ✗ tile build
name: test-tile
icon: resources/icon.png
label: Generated Test Tile
description: A sample tile generated by tile-generator
version: 0.0.1

bosh init release
bosh generate package app1
bosh generate job deploy-app-app1
bosh generate job delete-app-app1
bosh generate package app2
bosh generate job deploy-app-app2
bosh generate job delete-app-app2
bosh generate package broker1
bosh generate job deploy-app-broker1
bosh generate job delete-app-broker1
bosh generate job register-broker-broker1
bosh generate job destroy-broker-broker1
bosh generate package broker2
bosh generate job deploy-app-broker2
bosh generate job delete-app-broker2
bosh generate job register-broker-broker2
bosh generate job destroy-broker-broker2
bosh generate package broker3
bosh generate job register-broker-broker3
bosh generate job destroy-broker-broker3
bosh generate package buildpack1
bosh generate job deploy-buildpack-buildpack1
bosh generate job delete-buildpack-buildpack1
bosh generate package buildpack2
bosh generate job deploy-buildpack-buildpack2
bosh generate job delete-buildpack-buildpack2
bosh generate job docker-bosh-docker-bosh1
bosh generate job deploy-app-docker-app
bosh generate job delete-app-docker-app
bosh generate job deploy-app-docker-app-broker
bosh generate job delete-app-docker-app-broker
bosh generate job register-broker-docker-app-broker
bosh generate job destroy-broker-docker-app-broker
bosh generate package blob1
bosh generate package cf_cli
bosh upload blobs
bosh create release --force --final --with-tarball --version 0.0.1

tile import release test-tile
tile import release docker
tile build docker release
Traceback (most recent call last):
  File "/home/df/workspace/tile-generator/tile", line 76, in <module>
    cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "/home/df/workspace/tile-generator/tile", line 46, in build_cmd
    build.build(config, verbose)
  File "/home/df/workspace/tile-generator/lib/build.py", line 24, in build
    create_tile(context)
  File "/home/df/workspace/tile-generator/lib/build.py", line 217, in create_tile
    docker_release = build_docker_release()
  File "/home/df/workspace/tile-generator/lib/build.py", line 241, in build_docker_release
    bash('./update')
  File "/home/df/workspace/tile-generator/lib/build.py", line 275, in bash
    return subprocess.check_output(argv, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, *_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by dwu-pivotal** [comment]
Sorry, forgot to init submodules

git submodule update --init
