### ISSUE TITLE
error when using pcf utility OverflowError: string longer than 2147483647 bytes python

### ISSUE THREAD

**Issue by svennela** [cf-platform-eng/tile-generator#173]
Customer is getting following error when uploading elastic run time to ops manager using pcf utility

OverflowError: string longer than 2147483647 bytes python

command I am using is

pcf import pcf-products/cf-1.8.10-build.1.pivotal

Full error stack

bash-4.3# pcf import pcf-products/cf-1.8.10-build.1.pivotal 
Traceback (most recent call last): 
File "/usr/bin/pcf", line 11, in <module> 
load_entry_point('tile-generator==3.0.8', 'console_scripts', 'pcf')() 
File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__ 
return self.main(*args, **kwargs) 
File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main 
rv = self.invoke(ctx) 
File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke 
return _process_result(sub_ctx.command.invoke(sub_ctx)) 
File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke 
return ctx.invoke(self.callback, **ctx.params) 
File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke 
return callback(*args, **kwargs) 
File "/usr/lib/python2.7/site-packages/tile_generator/pcf.py", line 132, in import_cmd 
opsmgr.upload('/api/products', zipfile) 
File "/usr/lib/python2.7/site-packages/tile_generator/opsmgr.py", line 181, in upload 
response = requests.post(url, auth=auth(creds), verify=False, files=files) 
File "/usr/lib/python2.7/site-packages/requests/api.py", line 111, in post 
return request('post', url, data=data, json=json, **kwargs) 
File "/usr/lib/python2.7/site-packages/requests/api.py", line 57, in request 
return session.request(method=method, url=url, **kwargs) 
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request 
resp = self.send(prep, **send_kwargs) 
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 585, in send 
r = adapter.send(request, **kwargs) 
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 403, in send 
timeout=timeout 
File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen 
chunked=chunked) 
File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request 
conn.request(method, url, **httplib_request_kw) 
File "/usr/lib/python2.7/httplib.py", line 1042, in request 
self._send_request(method, url, body, headers) 
File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request 
self.endheaders(body) 
File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders 
self._send_output(message_body) 
File "/usr/lib/python2.7/httplib.py", line 882, in _send_output 
self.send(msg) 
File "/usr/lib/python2.7/httplib.py", line 858, in send 
self.sock.sendall(data) 
File "/usr/lib/python2.7/ssl.py", line 753, in sendall 
v = self.send(data[count:]) 
File "/usr/lib/python2.7/ssl.py", line 719, in send 
v = self._sslobj.write(data) 
OverflowError: string longer than 2147483647 bytes

**Comment by guidowb** [comment]
This is a known limitation of the Python requests library. Since Ops Manager expects a multipart form, the request library does not support streaming. There is, however, a companion request-toolbelt library that supports streaming multipart uploads. Will take a stab at using that instead.
