### ISSUE TITLE
Github API Errors

### ISSUE THREAD

**Issue by gmmeyer** [cf-platform-eng/tile-generator#241]
If you make too many requests from the same IP from the github api, it will rate limit you.

So, if you're rate limited, you cannot download the meta-buildpack. Can we have a way to put a github api token into the request header, so that we can get around the rate limit? Currently it just sends an empty request, but if you have a github api token, you could easily use the token to authenticate against the api.

```
$ tile build 0.0.3
name: datadog-cloudfoundry-buildpack
label: Datadog Cloud Foundry Buildpack
description: Send Cloud Foundry Application Metrics and Traces to Datadog!
version: 0.0.3
sha1: False
stemcell: ubuntu-trusty 3468

bosh download release meta-buildpack
Traceback (most recent call last):
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/bin/tile", line 11, in <module>
    sys.exit(cli())
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/tile_generator/tile.py", line 70, in build_cmd
    build.build(cfg)
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/tile_generator/build.py", line 46, in build
    build_bosh_releases(config)
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/tile_generator/build.py", line 54, in build_bosh_releases
    tarball = bosh_release.get_tarball()
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/tile_generator/bosh.py", line 82, in get_tarball
    return self.download_tarball()
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/tile_generator/bosh.py", line 88, in download_tarball
    download(self.path, tarball, self.context.get('cache', None))
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/tile_generator/util.py", line 63, in download
    response.raise_for_status()
  File "/Users/gregmeyer/.pyenv/versions/2.7.13/envs/cloudfoundry-buildpack/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/cf-platform-eng/meta-buildpack/releases/latest
```

**Comment by mboldt** [comment]
How about we look for an environment variable called `GITHUB_API_TOKEN`, and use that if it is present?

As a workaround, to avoid repeated downloads like this, you can use the `--cache` option.
```
mkdir cache
tile build --cache cache
```
This will put all downloads into the `cache` directory, and only download files if they are not already in the cache. (Note the `--cache` option is pretty fragile, e.g., make sure the directory exists before running `tile build`.)
