### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/tmp/tmpoW5Idw/chart/images/tiller.tgz'

### ISSUE THREAD

**Issue by macevil** [cf-platform-eng/tile-generator#262]
hi, i'm using the tile-generator:latest docker image and get the following error during `tile build`:

```
Traceback (most recent call last):
  File "/usr/bin/tile", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tile_generator/tile.py", line 72, in build_cmd
    build.build(cfg)
  File "/usr/lib/python2.7/site-packages/tile_generator/build.py", line 48, in build
    build_bosh_releases(config)
  File "/usr/lib/python2.7/site-packages/tile_generator/build.py", line 56, in build_bosh_releases
    tarball = bosh_release.get_tarball()
  File "/usr/lib/python2.7/site-packages/tile_generator/bosh.py", line 83, in get_tarball
    return self.build_tarball()
  File "/usr/lib/python2.7/site-packages/tile_generator/bosh.py", line 104, in build_tarball
    self.add_package(package)
  File "/usr/lib/python2.7/site-packages/tile_generator/bosh.py", line 203, in add_package
    download(file['path'], os.path.join(staging_dir, file['name']), cache=self.context.get('cache', None))
  File "/usr/lib/python2.7/site-packages/tile_generator/util.py", line 82, in download
    with open(filename, 'wb') as file:
IOError: [Errno 2] No such file or directory: '/tmp/tmpoW5Idw/chart/images/tiller.tgz'
```

**Comment by macevil** [comment]
yeah! i found the problem, the 

> helm_chart_dir: directory/to/helm/chart

was wrong and there were no images folder.

**Comment by mboldt** [comment]
Also, make sure you add the images folder to your helm chart's `.helmignore`. (I think we have a PR to docs to include this step, and automating it is on the backlog, but a ways down.)

**Comment by cholick** [comment]
You can skip the `.helmignore` if it only contains `images`, we're doing that programmatically at this point: https://github.com/cf-platform-eng/kibosh/commit/7e405aa447408330bc3e3a58ffc3e2fa606d99ae
