### ISSUE TITLE
Lots of places can use better error detection and messages

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#57]
For instance:

```
pez-03 pcf import sample/product/test-tile-0.3.72.pivotal
Traceback (most recent call last):
  File "/Users/gwestenberg/git/tile-generator/bin/pcf", line 200, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/gwestenberg/git/tile-generator/bin/pcf", line 77, in import_cmd
    opsmgr.upload('/api/products', zipfile)
  File "/Users/gwestenberg/git/tile-generator/bin/../lib/opsmgr.py", line 92, in upload
    files = { 'product[file]': open(filename, 'rb') }
IOError: [Errno 2] No such file or directory: u'sample/product/test-tile-0.3.72.pivotal'
```

**Comment by keshto** [comment]
Closing due to date and the amount of code change since. Please feel free to open another issue if you observe similar behaviour
